force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Hours_Worked_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Hours_Worked_To_Date__c</fullName>
    <label>Hours Worked To Date</label>
    <summarizedField>Timesheet__c.Total_Hours__c</summarizedField>
    <summaryForeignKey>Timesheet__c.Project_Name__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectController.cls
public with sharing class ProjectController {

    @AuraEnabled(Cacheable=true)
    public static List<Project__c>  getProjects() {
        return [
            SELECT
            Id,
            Name,
            Account_Name__r.Name,
            Opportunity_Name__r.Name,
            Start_Date__c,
            End_Date__c,
            Hours_Worked_To_Date__c,
            Total_Hours__c
        FROM Project__c
        ORDER BY LastModifiedDate DESC
        LIMIT 10];
    }
    @AuraEnabled(Cacheable=true)
    public static Project__c getProjectBiId(Id project_Id) {
        return [
            SELECT
                Id,
                Name,
                Account_Name__r.Name,
                Opportunity_Name__r.Name,
                Start_Date__c,
                End_Date__c,
                Hours_Worked_To_Date__c,
                Total_Hours__c
            FROM Project__c
            WHERE Id = :project_Id
        ];
    }

}